#!/usr/bin/env bash

command -v curl >/dev/null 2>&1 || { echo >&2 "Please install curl before continuing"; exit 1; }
command -v git >/dev/null 2>&1 || { echo >&2 "Please install git before continuing"; exit 1; }

cp mpv/input.conf ~/.config/input.conf
cp mpv/mpv.conf ~/.config/mpv.conf

curl --fail --output ~/.zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
cp zshrc.local ~/.zshrc.local
cp shell_aliases ~/.shell_aliases
git clone "https://github.com/zsh-users/zsh-syntax-highlighting.git"
git clone "https://github.com/zsh-users/zsh-autosuggestions.git"
sudo mv zsh-syntax-highlighting/ /usr/local/share/
sudo mv zsh-users/zsh-autosuggestions/ /usr/local/share/

curl --fail --create-dirs --output ~/.vim/colors/molokai.vim https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim
curl --fail --create-dirs --output ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

command -v mpv >/dev/null 2>&1 || echo "Recommended: Install mpv to make use of mpv config files"
