#!/usr/bin/env bash

echo -e "Checking configuration...\n"
PLATFORM="$(uname -s)"
command -v curl >/dev/null 2>&1 || { echo >&2 "Please install curl before continuing"; exit 1; }
command -v git >/dev/null 2>&1 || { echo >&2 "Please install git before continuing"; exit 1; }
command -v vim >/dev/null 2>&1 || { echo >&2 "Please install vim before continuing"; exit 1; }
if [ "$PLATFORM" == "Darwin" ]; then
  command -v brew >/dev/null 2>&1 || { echo >&2 "PLease install brew before continuing"; exit 1; }
fi

echo -e "Setting up fzf...\n"
if [ "$PLATFORM" == "Darwin" ]; then
  brew install fzf && /usr/local/opt/fzf/install
else
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
fi

echo -e "Setting up vim...\n"
mkdir -p ~/.vim/autoload
mkdir -p ~/.vim/colors
cp -R vim/. ~/.vim/
cp vimrc ~/.vimrc
vim  +PlugInstall +qall > /dev/null 2>&1
