command_timeout = 1000

format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$bun\
$golang\
$helm\
$nodejs\
$python\
$ruby\
$rust\
$terraform\
$zig\
$line_break\
$jobs\
$time\
$status\
$container\
$character"""
