command_timeout = 1000

format = """
$username\
$hostname\
$localip\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$python\
$rlang\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$typst\
$zig\
$nix_shell\
$memory_usage\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$line_break\
$jobs\
$time\
$status\
$os\
$container\
$shell\
$character"""
