call plug#begin()
  Plug 'vim-airline/vim-airline'
  Plug 'joshdick/onedark.vim'
call plug#end()

syntax on
colorscheme onedark

set expandtab
set tabstop=2

set backspace=indent,eol,start

set encoding=utf-8

set relativenumber

let g:netrw_banner=0
let g:netrw_browse_split=4
let g:netrw_liststyle=3
let g:netrw_winsize=25

let mapleader = ","
nnoremap <leader>q :qa<CR>
nnoremap <leader>w <c-w><c-w>
nnoremap <leader>e :Lexplore<CR>
