call plug#begin()
  Plug 'vim-airline/vim-airline'
  Plug 'joshdick/onedark.vim'
call plug#end()

syntax on
colorscheme onedark

set backspace=indent,eol,start
set encoding=utf-8

set expandtab
set tabstop=2

set relativenumber

let mapleader = ","
