# vim: syntax=config

MOUSE_BTN2 keypress SPACE

SPACE          cycle pause
ENTER          cycle fullscreen
ESC            show-progress

m              cycle mute
o              cycle osc

CTRL+j         add sub-scale +0.1
CTRL+k         add sub-scale -0.1

ALT+RIGHT      add video-rotate 90
ALT+LEFT       add video-rotate -90

ALT+-          add video-zoom -0.25
ALT+=          add video-zoom 0.25

1              set window-scale 0.25
2              set window-scale 0.5
3              set window-scale 0.75
4              set window-scale 1
5              set window-scale 1.25
6              set window-scale 1.5
7              set window-scale 1.75
8              set window-scale 2
9              set window-scale 2.25

