# vim: syntax=config

## GENERAL

border=no
ontop=yes
autofit-larger=90%x90%
cursor-autohide=1000
prefetch-playlist=yes
force-seekable=yes

## OSD

osd-level=1
osd-bar-align-y=0
osd-bar-h=4
osd-border-size=0.4
osd-color='#CCFFFFFF'
osd-border-color='#99000000'
osd-font="Hiragino Maru Gothic Pro"
osd-playing-msg='file: ${filename}'
osd-duration=2000

## VIDEO

vo=gpu
hwdec=auto

## AUDIO

audio-pitch-correction=yes
volume-max=200

# SUBTITLES

sub-auto=fuzzy
demuxer-mkv-subtitle-preroll
embeddedfonts=yes
sub-fix-timing=no
sub-ass-force-style=Kerning=yes
sub-use-margins
sub-ass-force-margins
# the following options only apply to subtitles without own styling
sub-font-size=30
sub-color="#FFFFFFFF"
sub-border-color="#FF262626"
sub-border-size=2.5
sub-shadow-offset=1
sub-shadow-color="#33000000"
sub-spacing=0.5

## SCREENSHOTS

screenshot-format=png
screenshot-png-compression=8
screenshot-template='~/Pictures/screenshots/%F (%P) %n'
